from __future__ import annotations

from ..models import LanguageConfig


_CPP_TEST_GLOBS = (
    "*_test.cpp",
    "**/*_test.cpp",
    "test_*.cpp",
    "**/test_*.cpp",
    "*_test.cc",
    "**/*_test.cc",
    "test_*.cc",
    "**/test_*.cc",
    "*_test.cxx",
    "**/*_test.cxx",
    "test_*.cxx",
    "**/test_*.cxx",
    "tests/*.cpp",
    "tests/**/*.cpp",
    "tests/*.cc",
    "tests/**/*.cc",
    "tests/*.cxx",
    "tests/**/*.cxx",
    "test/*.cpp",
    "test/**/*.cpp",
    "test/*.cc",
    "test/**/*.cc",
    "test/*.cxx",
    "test/**/*.cxx",
    "**/tests/*.cpp",
    "**/tests/**/*.cpp",
    "**/tests/*.cc",
    "**/tests/**/*.cc",
    "**/tests/*.cxx",
    "**/tests/**/*.cxx",
    "**/test/*.cpp",
    "**/test/**/*.cpp",
    "**/test/*.cc",
    "**/test/**/*.cc",
    "**/test/*.cxx",
    "**/test/**/*.cxx",
)


CPP_CONFIG = LanguageConfig(
    name="cpp",
    display_name="C++",
    extensions=(".cpp", ".cc", ".cxx", ".hpp", ".hh", ".hxx"),
    markdown_fence="cpp",
    source_globs=(
        "*.cpp",
        "**/*.cpp",
        "*.cc",
        "**/*.cc",
        "*.cxx",
        "**/*.cxx",
        "*.hpp",
        "**/*.hpp",
        "*.hh",
        "**/*.hh",
        "*.hxx",
        "**/*.hxx",
    ),
    test_globs=_CPP_TEST_GLOBS,
    tree_sitter_language="cpp",
    class_node_types=("class_specifier", "struct_specifier"),
    function_node_types=("function_definition",),
    method_node_types=("function_definition",),
    import_node_types=("preproc_include",),
    module_path_style="c",
    dependency_files=("CMakeLists.txt", "Makefile", "compile_commands.json", "CMakePresets.json"),
    entrypoint_candidates=("main.cpp", "src/main.cpp", "main.cc", "src/main.cc"),
)
