from __future__ import annotations

import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]
_SCRIPTS = _REPO / "scripts"
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from common.dashboard_report import write_dashboard_report


def _snapshot(*, with_graph: bool = True) -> dict:
    root = {
        "id": "repo",
        "name": "demo",
        "node_type": "repo",
        "children": [{"id": "feature-a", "name": "Feature A", "node_type": "feature", "children": []}],
    }
    return {
        "schema_version": "1.0",
        "generated_at": "2026-08-04T00:00:00Z",
        "workspace": {"name": "demo", "mode": "encoder"},
        "rpg": {"repo_name": "demo"},
        "graph": {
            "feature_root": root if with_graph else None,
            "semantic_edges": [],
            "dependency_graph": {"nodes": {}, "edges": []},
            "dep_to_rpg_map": {},
        },
        "rpg_latest_change": {
            "available": True,
            "short_commit": "new12345",
            "parent_short": "old12345",
            "operation": "update-rpg",
            "feature_nodes": {
                "added": [],
                "removed": [],
                "modified": [{
                    "node_id": "feature-a",
                    "name": "Feature A",
                    "node_type": "feature",
                    "path": "src/a.py",
                    "parent_id": "repo",
                    "previous_parent_id": "repo",
                    "changed_fields": ["meta"],
                }],
                "counts": {"added": 0, "removed": 0, "modified": 1, "total": 2},
            },
            "dependency_nodes": {"added": [], "removed": [], "modified": [], "counts": {"added": 0, "removed": 0, "modified": 0, "total": 0}},
            "semantic_edges": {"added": [], "removed": [], "counts": {"added": 0, "removed": 0, "total": 0}},
            "dependency_edges": {"added": [], "removed": [], "counts": {"added": 0, "removed": 0, "total": 0}},
            "feature_hierarchy_edges": {"added": [], "removed": [], "counts": {"added": 0, "removed": 0, "total": 1}},
            "mapping_edges": {"added": [], "removed": [], "counts": {"added": 0, "removed": 0, "total": 0}},
        },
        "pipeline": [],
        "runs": [],
        "source_health": [],
        "artifacts": [],
    }


def test_writes_complete_static_report(tmp_path: Path) -> None:
    snapshot = _snapshot()
    outputs = write_dashboard_report(snapshot, tmp_path / "reports")

    for output in (
        outputs.report_html,
        outputs.report_data_js,
        outputs.rpg_html,
        outputs.report_css,
        outputs.report_js,
    ):
        assert output.is_file()
        assert output.stat().st_size > 0

    report_html = outputs.report_html.read_text(encoding="utf-8")
    report_js = outputs.report_js.read_text(encoding="utf-8")
    report_data = outputs.report_data_js.read_text(encoding="utf-8")
    rpg_html = outputs.rpg_html.read_text(encoding="utf-8")

    assert 'src="report-data.js"' in report_html
    assert 'src="assets/report.js"' in report_html
    assert 'href="assets/report.css"' in report_html
    assert "fetch(" not in report_html
    assert "fetch(" not in report_js
    assert 'data-view="features"' not in report_html
    assert 'id="view-features"' not in report_html
    assert "renderFeatures" not in report_js
    assert '"features"' not in report_js
    assert "Feature plan" not in report_js
    assert "Pipeline readiness and stage evidence" in report_js
    assert "no evidence" in report_js
    assert "Source availability" in report_js
    assert "artifact present" in report_js
    assert 'data-pipeline-jump="' in report_js
    assert 'id="pipeline-' in report_js
    assert 'location.hash = "pipeline/"' in report_js
    assert "scrollIntoView" in report_js
    assert "pipeline-jump-highlight" in report_js
    assert '<iframe class="ready" id="rpgFrame"' in report_js
    assert 'id="rpgFrame" src="rpg.html"' not in report_js
    assert "frameElement.srcdoc = RPG_DOCUMENT" in report_js
    assert "contentWindow.d3" not in report_js
    assert "rpgFallback" not in report_js
    assert report_data.startswith("// Generated by CoderMind")
    embedded_rpg = json.loads(
        report_data.split("window.CMIND_RPG_HTML = ", 1)[1]
        .split(";\nwindow.CMIND_REPORT = ", 1)[0]
    )
    payload = json.loads(report_data.split("window.CMIND_REPORT = ", 1)[1].rsplit(";", 1)[0])
    assert payload["workspace"]["name"] == "demo"
    assert embedded_rpg == rpg_html
    assert "const hasChangeData = true;" in rpg_html
    assert "old12345" in rpg_html
    assert "Current Changes" in rpg_html
    assert "@media (max-width: 600px)" in rpg_html
    assert "#search { width: 62px; min-width: 62px" in rpg_html
    assert "'arrow-rel-' + relation" in rpg_html
    assert "drawn relations" in rpg_html
    assert "Directed relations" in rpg_html
    assert "Node fill · code type" in rpg_html
    assert "function / method" in rpg_html
    assert "let cpOpen = true;" in rpg_html
    assert "fill: #e6edf3" in rpg_html
    assert ":root[data-theme=\"light\"] .change-graph-node .node-label" in rpg_html
    assert "<b>${changeNodeGlyph(r.status)}</b>${statusLabel}" in rpg_html
    assert "btn.textContent = cpOpen ? 'Hide changes' : 'Show changes';" in rpg_html
    assert "function dependencyDisplayLabel(node)" in rpg_html
    assert "function placeChangeGraphLabels(selection, forceNodeById)" in rpg_html
    assert "repository root" in rpg_html
    assert "drawChangeGraph();" in rpg_html
    assert ".change-graph-node { pointer-events: all; cursor: pointer;" in rpg_html
    assert ".change-graph-link.focus-related" in rpg_html
    assert ".change-graph-link.focus-dim" in rpg_html
    assert ".change-graph-node.focus-neighbor" in rpg_html
    assert ".change-graph-node.focus-dim" in rpg_html
    assert "const sameDependencyFocus" in rpg_html
    assert "click.change-deselect" in rpg_html
    assert "if (depSelectedNodes.size > 0) depUpdateNodeHighlight();" in rpg_html
    assert "externalChanges.mode !== 'full' || !externalChanges.emphasize" in rpg_html
    assert "if (externalChanges.mode === 'changes')" in rpg_html
    assert "#canvas { cursor: grab; }" in rpg_html
    assert "gChange.style('display', null);\n  svg.on('.zoom', null).call(zoomChange);" in rpg_html
    assert "function buildFullDependencyGraph()" in rpg_html
    assert "const graph = externalChanges.mode === 'full' ? buildFullDependencyGraph() : buildChangeGraph(scope);" in rpg_html
    assert "if (activeTab === 'dep' && typeof drawChangeGraph === 'function')" in rpg_html
    assert "if (scope === 'dependency' && activeTab === 'dep')" in rpg_html
    assert "fill: var(--node-fill,#484f58)" in rpg_html
    assert ".style('--node-fill', node => nodeTypeColors[node.node_type] || nodeTypeColors.default)" in rpg_html
    assert "externalChanges.mode !== 'changes' && !externalChanges.emphasize" in rpg_html
    assert "const featureFocusId = externalChanges.focus?.scope === 'feature'" in rpg_html
    assert not list((tmp_path / "reports").rglob("*.tmp"))


def test_missing_feature_graph_uses_empty_root(tmp_path: Path) -> None:
    outputs = write_dashboard_report(_snapshot(with_graph=False), tmp_path / "reports")
    rpg_html = outputs.rpg_html.read_text(encoding="utf-8")
    report_js = outputs.report_js.read_text(encoding="utf-8")

    assert '"id": "__empty__"' in rpg_html
    assert "RPG: demo" in rpg_html
    assert "RPG not generated" in report_js
    assert "No <span class=\"mono\">rpg.json</span>" in report_js


def test_uses_configured_local_d3_bundle(tmp_path: Path, monkeypatch) -> None:
    d3_source = tmp_path / "d3.v7.min.js"
    d3_source.write_text("/* local d3 test bundle */\n", encoding="utf-8")
    monkeypatch.setenv("CMIND_D3_PATH", str(d3_source))

    outputs = write_dashboard_report(_snapshot(), tmp_path / "reports")

    assert outputs.d3_js is not None
    assert outputs.d3_js.read_text(encoding="utf-8") == "/* local d3 test bundle */\n"
    rpg_html = outputs.rpg_html.read_text(encoding="utf-8")
    assert 'src="assets/d3.v7.min.js"' in rpg_html
    assert "https://d3js.org/d3.v7.min.js" not in rpg_html
