"""Generate the static CoderMind dashboard report from a validated snapshot."""

from __future__ import annotations

import json
import os
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from common.paths import REPORTS_DIR
from rpg_visualize import generate_html

_ASSET_SOURCE_DIR = Path(__file__).resolve().parent / "report_assets"


@dataclass(frozen=True)
class DashboardReportOutputs:
    report_html: Path
    report_data_js: Path
    rpg_html: Path
    report_css: Path
    report_js: Path
    d3_js: Path | None


def _atomic_write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary_path, path)
    finally:
        temporary_path.unlink(missing_ok=True)


def _asset(name: str) -> str:
    return (_ASSET_SOURCE_DIR / name).read_text(encoding="utf-8")


def _d3_source() -> Path | None:
    configured = os.environ.get("CMIND_D3_PATH")
    candidates = [Path(configured).expanduser()] if configured else []
    candidates.append(_ASSET_SOURCE_DIR / "d3.v7.min.js")
    return next((candidate for candidate in candidates if candidate.is_file()), None)


def _rpg_input(snapshot: dict[str, Any]) -> dict[str, Any]:
    graph = snapshot.get("graph") if isinstance(snapshot.get("graph"), dict) else {}
    rpg = snapshot.get("rpg") if isinstance(snapshot.get("rpg"), dict) else {}
    workspace = snapshot.get("workspace") if isinstance(snapshot.get("workspace"), dict) else {}
    repo_name = rpg.get("repo_name") or workspace.get("name") or "repository"
    root = graph.get("feature_root")
    if not isinstance(root, dict):
        root = {
            "id": "__empty__",
            "name": repo_name,
            "node_type": "repo",
            "children": [],
        }
    return {
        "repo_name": repo_name,
        "root": root,
        "edges": graph.get("semantic_edges") if isinstance(graph.get("semantic_edges"), list) else [],
        "dep_graph": graph.get("dependency_graph") if isinstance(graph.get("dependency_graph"), dict) else {},
        "_dep_to_rpg_map": graph.get("dep_to_rpg_map") if isinstance(graph.get("dep_to_rpg_map"), dict) else {},
    }


def write_dashboard_report(
    snapshot: dict[str, Any],
    reports_dir: Path | None = None,
) -> DashboardReportOutputs:
    """Write the complete file://-openable report and return its output paths."""
    target = Path(reports_dir) if reports_dir is not None else REPORTS_DIR
    assets_dir = target / "assets"
    d3_source = _d3_source()
    outputs = DashboardReportOutputs(
        report_html=target / "report.html",
        report_data_js=target / "report-data.js",
        rpg_html=target / "rpg.html",
        report_css=assets_dir / "report.css",
        report_js=assets_dir / "report.js",
        d3_js=assets_dir / "d3.v7.min.js" if d3_source is not None else None,
    )

    change_data = snapshot.get("rpg_latest_change")
    if not isinstance(change_data, dict) or not change_data.get("available"):
        change_data = None
    rpg_html = generate_html(_rpg_input(snapshot), change_data)
    if d3_source is not None:
        rpg_html = rpg_html.replace("https://d3js.org/d3.v7.min.js", "assets/d3.v7.min.js")
    payload = json.dumps(snapshot, ensure_ascii=False, separators=(",", ":"))
    embedded_rpg = json.dumps(rpg_html, ensure_ascii=True)
    report_data = (
        "// Generated by CoderMind; do not edit by hand.\n"
        f"window.CMIND_RPG_HTML = {embedded_rpg};\n"
        f"window.CMIND_REPORT = {payload};\n"
    )

    # Publish dependencies first and the entry point last so readers never see a
    # new report.html before its matching data and assets are available.
    _atomic_write_text(outputs.report_css, _asset("report.css"))
    _atomic_write_text(outputs.report_js, _asset("report.js"))
    if d3_source is not None and outputs.d3_js is not None:
        _atomic_write_text(outputs.d3_js, d3_source.read_text(encoding="utf-8"))
    _atomic_write_text(outputs.report_data_js, report_data)
    _atomic_write_text(outputs.rpg_html, rpg_html)
    _atomic_write_text(outputs.report_html, _asset("report.html"))
    return outputs
