#!/usr/bin/env python3
"""Inspect feature tree state and decide execution state for feature_edit.

Decision rules:
- Check if .cmind/data/feature_tree.json exists
- Check if 'components' field exists and is not empty (generated by feature_refactor)
- Check if repository_name exists and is not empty
- Accept edit_instruction parameter and save to feature_tree.json
- Maintain instruction history with UTC timestamps

The script prints EXACTLY ONE JSON object to stdout.
No extra text is allowed.
"""

import json
import sys
import argparse
from pathlib import Path
from typing import Any, Dict

from common.paths import FEATURE_TREE_FILE


def load_json(path: Path) -> Dict[str, Any] | None:
    """Load JSON file and return data, or None if failed."""
    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
            if isinstance(data, dict) and len(data) > 0:
                return data
    except Exception:
        pass
    return None


def save_json(path: Path, data: Dict[str, Any]) -> None:
    """Save JSON data to file."""
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
    except Exception as e:
        print(
            json.dumps({"error": f"Failed to save file: {str(e)}"}, ensure_ascii=False),
            file=sys.stderr,
        )


def update_instructions(data: Dict[str, Any], new_instructions: str) -> Dict[str, Any]:
    """Update edit_instruction field only.

    Note: edit_history is managed by feature_edit.py after successful execution.
    This function only:
    1. Initializes edit_history if not exists
    2. Cleans up duplicate/legacy entries (keeps the one with most info)
    3. Sets edit_instruction

    Args:
        data: Current JSON data
        new_instructions: New instruction text (can be empty)

    Returns:
        Updated data with edit_instruction
    """
    # Initialize edit_history if not exists
    if "edit_history" not in data:
        data["edit_history"] = []

    # Clean up: for duplicate instructions, keep the one with more fields (from feature_edit.py)
    cleaned_history = []
    seen_instructions = {}  # instruction -> (index, entry)

    for entry in data["edit_history"]:
        if isinstance(entry, dict) and "instruction" in entry:
            instruction_text = entry["instruction"]
            entry_fields = len(entry)

            if instruction_text in seen_instructions:
                # Keep the entry with more fields (more complete record)
                existing_idx, existing_entry = seen_instructions[instruction_text]
                if entry_fields > len(existing_entry):
                    # Replace with the more complete entry
                    seen_instructions[instruction_text] = (len(cleaned_history), entry)
                    cleaned_history[existing_idx] = entry
                # else: keep existing, skip this one
            else:
                seen_instructions[instruction_text] = (len(cleaned_history), entry)
                cleaned_history.append(entry)
        elif isinstance(entry, str):
            # Skip legacy string format
            pass

    data["edit_history"] = cleaned_history

    # Update current instructions (edit_history is added by feature_edit.py after execution)
    data["edit_instruction"] = new_instructions

    return data


def inspect_state(edit_instruction: str = "") -> Dict[str, Any]:
    """Inspect repository state and return a decision object.

    Logic:
    - Check if feature_tree.json exists and has valid feature_tree field
    - Save edit_instruction to the file

    Args:
        edit_instruction: User's edit instructions to save

    Returns:
        Decision object with type field: "ready" or "error"
    """
    # Check if feature_tree.json exists
    if not FEATURE_TREE_FILE.exists():
        return {
            "type": "error",
            "error_code": "file_not_found",
            "message": f"Input file '{FEATURE_TREE_FILE}' does not exist. Please run /cmind.feature_refactor first.",
            "file": str(FEATURE_TREE_FILE),
        }

    # Load feature_tree.json
    data = load_json(FEATURE_TREE_FILE)

    if data is None:
        return {
            "type": "error",
            "error_code": "file_invalid",
            "message": f"File '{FEATURE_TREE_FILE}' is empty or contains invalid JSON.",
            "file": str(FEATURE_TREE_FILE),
        }

    # Check if components field exists and is not empty
    components = data.get("components")
    if not components or not isinstance(components, list) or len(components) == 0:
        return {
            "type": "error",
            "error_code": "field_empty",
            "message": f"Field 'components' is missing or empty in '{FEATURE_TREE_FILE}'. Please run /cmind.feature_refactor to generate components.",
            "file": str(FEATURE_TREE_FILE),
            "missing_field": "components",
        }

    # Check required fields
    repository_name = data.get("repository_name", "")

    if not repository_name:
        return {
            "type": "error",
            "error_code": "field_missing",
            "message": "Field 'repository_name' is missing or empty in the file.",
            "file": str(FEATURE_TREE_FILE),
            "missing_field": "repository_name",
        }

    # Update with user instructions
    data = update_instructions(data, edit_instruction)

    # Save updated file
    save_json(FEATURE_TREE_FILE, data)

    # Return ready status
    return {
        "type": "ready",
        "file": str(FEATURE_TREE_FILE),
        "components_count": len(components),
        "edit_instruction": edit_instruction,
        "message": "Ready to execute feature_edit.py",
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Check edit feature prerequisites and save user instructions"
    )
    parser.add_argument(
        "--edit_instruction",
        type=str,
        default="",
        help="User edit instructions for the feature tree (required)",
    )

    args = parser.parse_args()

    decision = inspect_state(args.edit_instruction)
    print(json.dumps(decision, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
